### ISSUE TITLE
Singularity Hub

### ISSUE THREAD

**Issue by vsoch** [IARCbioinfo/template-nf#1]
hey IARCbioinfo! ! I'm really glad to see that you guys are taking advantage of Singularity Hub! :) Would you mind deleting builds that you no longer need? It looks like you just hit 20 (all successful) and since we are storing (and paying for) each build, it's good container hygiene to keep this sort of thing in mind. If needed, you can also disable building for times when you anticipate high levels of commits, or just use a different branch for releases / Singularity Hub. Thank you!

**Comment by mfoll** [comment]
We now use docker hub only to host containers

**Comment by vsoch** [comment]
Sounds good! You can pull with the `docker://` uri. Happy building!
