### ISSUE TITLE
improve SingularityHub deployment

### ISSUE THREAD

**Issue by tdelhomme** [IARCbioinfo/template-nf#4]
At the moment, the deployment on SingularityHub is done only for github pushes on the `Singularity` file. Since our container depends on two files (`environment.yml` and the `singularity`), this means that triggers are not well defined.
See this discussion:
https://github.com/singularityhub/singularityhub.github.io/issues/142#issuecomment-411442424

**Comment by vsoch** [comment]
If you'd like some kind of custom deployment, then you can do this by way of setting up continuous integration for your repo that does a final commit to master (perhaps with a version string in the Singularity file?) to trigger the build. This time strategy has to be done to resolve conflicts between two builds that would have the same tag (given the same named Singularity files). If you find the default on commit doesn't work for you, the commit on deploy is an alternative, along with manual build.
